# Generated by Django 4.2.5 on 2023-10-21 18:26

import app_base.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'Bu isimde bir kullanici zaten var'}, help_text='Max 150 karakter olabilir. Harfler, sayilar ve sadece @/./+/-/_ olabilir', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Kullanıcı Adı')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='İsim')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Soyisim')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Kullanıcının bu yönetici paneline giriş yapabilmesini belirler.', verbose_name='Yönetici Durumu')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Islemler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('islem_ismi', models.CharField(max_length=250)),
                ('islem_aciklamasi', models.TextField()),
                ('miktar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('islemler_picture', models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename)),
                ('islemler_pdf', models.FileField(blank=True, null=True, upload_to=app_base.models.generate_unique_filename)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_base.currency')),
                ('islemsahibi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('kimden_geldi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelen_paralar', to=settings.AUTH_USER_MODEL)),
                ('kime_gitti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='giden_paralar', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='app_base.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EvrakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_date', models.DateTimeField(auto_now_add=True)),
                ('evrak_last_updated', models.DateTimeField(auto_now=True)),
                ('evrak_name', models.CharField(max_length=250)),
                ('evrak_description', models.TextField()),
                ('evrak_type', models.CharField(choices=[('gelen', 'Gelen'), ('giden', 'Giden')], default='gelen', max_length=7)),
                ('evrak_picture', models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename)),
                ('evrak_pdf', models.FileField(blank=True, null=True, upload_to=app_base.models.generate_unique_filename)),
                ('evrak_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evrak_tags', models.ManyToManyField(blank=True, to='app_base.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EtkinlikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_date', models.DateTimeField(auto_now_add=True)),
                ('etkinlik_last_updated', models.DateTimeField(auto_now=True)),
                ('etkinlik_name', models.CharField(max_length=250)),
                ('etkinlik_description', models.TextField()),
                ('etkinlik_youtubelink', models.CharField(blank=True, max_length=200, null=True)),
                ('etkinlik_picture', models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename)),
                ('etkinlik_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('etkinlik_tags', models.ManyToManyField(blank=True, to='app_base.tag')),
            ],
        ),
        migrations.AddField(
            model_name='muuser',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_base.currency'),
        ),
        migrations.AddField(
            model_name='muuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='muuser',
            name='gruplar',
            field=models.ManyToManyField(blank=True, to='app_base.mugroup'),
        ),
        migrations.AddField(
            model_name='muuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
