# Generated by Django 4.2.5 on 2023-09-14 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muuser',
            name='bakiye_Dolar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='bakiye_Euro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='bakiye_GBP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='bakiye_Sek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='bakiye_TL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='ciktilar_Dolar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='ciktilar_Euro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='ciktilar_GBP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='ciktilar_TL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='girdiler_Dolar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='girdiler_Euro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='girdiler_GBP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='girdiler_TL',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Islemler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateField(auto_now=True)),
                ('islem_ismi', models.CharField(max_length=250)),
                ('islem_aciklamasi', models.TextField()),
                ('bakiye_TL', models.IntegerField(default=0)),
                ('girdiler_TL', models.IntegerField(default=0)),
                ('ciktilar_TL', models.IntegerField(default=0)),
                ('bakiye_Euro', models.IntegerField(default=0)),
                ('girdiler_Euro', models.IntegerField(default=0)),
                ('ciktilar_Euro', models.IntegerField(default=0)),
                ('bakiye_Dolar', models.IntegerField(default=0)),
                ('girdiler_Dolar', models.IntegerField(default=0)),
                ('ciktilar_Dolar', models.IntegerField(default=0)),
                ('bakiye_GBP', models.IntegerField(default=0)),
                ('bakiye_Sek', models.IntegerField(default=0)),
                ('girdiler_GBP', models.IntegerField(default=0)),
                ('ciktilar_GBP', models.IntegerField(default=0)),
                ('islemsahibi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
