# Generated by Django 4.2.6 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evrakmodel',
            name='evrak_takipno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
