# Generated by Django 4.2.5 on 2023-10-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_alter_muuser_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islemler',
            old_name='ciktilar',
            new_name='miktar',
        ),
        migrations.RemoveField(
            model_name='islemler',
            name='girdiler',
        ),
    ]
