# Generated by Django 4.2.5 on 2023-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_muuser_bakiye_dolar_muuser_bakiye_euro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='islemler',
            name='ciktilar_Sek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islemler',
            name='girdiler_Sek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='ciktilar_Sek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muuser',
            name='girdiler_Sek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islemler',
            name='tags',
            field=models.ManyToManyField(to='app_base.tag'),
        ),
    ]
