# Generated by Django 4.2.5 on 2023-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_dummymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
