# Generated by Django 4.2.5 on 2023-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_alter_muuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muuser',
            name='password',
            field=models.CharField(default=34, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
