# Generated by Django 4.2.5 on 2023-09-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_tag_islemler_ciktilar_sek_islemler_girdiler_sek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islemler',
            old_name='bakiye_Dolar',
            new_name='bakiye_ilk_Dolar',
        ),
        migrations.RenameField(
            model_name='islemler',
            old_name='bakiye_Euro',
            new_name='bakiye_ilk_Euro',
        ),
        migrations.RenameField(
            model_name='islemler',
            old_name='bakiye_GBP',
            new_name='bakiye_ilk_GBP',
        ),
        migrations.RenameField(
            model_name='islemler',
            old_name='bakiye_Sek',
            new_name='bakiye_ilk_Sek',
        ),
        migrations.RenameField(
            model_name='islemler',
            old_name='bakiye_TL',
            new_name='bakiye_ilk_TL',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='ciktilar_Dolar',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='ciktilar_Euro',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='ciktilar_GBP',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='ciktilar_Sek',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='ciktilar_TL',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='girdiler_Dolar',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='girdiler_Euro',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='girdiler_GBP',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='girdiler_Sek',
        ),
        migrations.RemoveField(
            model_name='muuser',
            name='girdiler_TL',
        ),
        migrations.AddField(
            model_name='islemler',
            name='kimden_geldi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelen_paralar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='islemler',
            name='kime_gitti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='giden_paralar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='islemler',
            name='islem_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
