# Generated by Django 4.2.5 on 2023-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_rename_ciktilar_islemler_miktar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islemler',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app_base.tag'),
        ),
    ]
