# Generated by Django 4.2.5 on 2023-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0004_alter_muuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExelUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
