# Generated by Django 4.2.5 on 2023-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_exelusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exelusers',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
