# Generated by Django 4.2.5 on 2023-10-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_alter_islemler_currency_alter_islemler_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muuser',
            name='gruplar',
            field=models.ManyToManyField(blank=True, null=True, to='app_base.mugroup'),
        ),
    ]
