# Generated by Django 4.2.5 on 2023-10-04 18:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_mugroup_alter_muuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='muuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Kullanıcının bu yönetici paneline giriş yapabilmesini belirler.', verbose_name='Yönetici Durumu'),
        ),
        migrations.AlterField(
            model_name='muuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='muuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bu isimde bir kullanici zaten var'}, help_text='Max 150 karakter olabilir. Harfler, sayilar ve sadece @/./+/-/_ olabilir', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Kullanıcı Adı'),
        ),
    ]
