# Generated by Django 4.2.5 on 2023-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0006_muuser_gruplar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muuser',
            name='gruplar',
            field=models.ManyToManyField(blank=True, to='app_base.mugroup'),
        ),
    ]
