# Generated by Django 4.2.5 on 2023-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_alter_exelusers_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='islemler',
            name='exelusers',
            field=models.ManyToManyField(blank=True, to='app_base.exelusers'),
        ),
    ]
