# Generated by Django 4.2.5 on 2023-10-19 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_alter_muuser_gruplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvrakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_date', models.DateTimeField(auto_now_add=True)),
                ('evrak_name', models.CharField(max_length=250)),
                ('evrak_description', models.TextField()),
                ('evrak_picture', models.ImageField(upload_to='images/')),
                ('evrak_pdf', models.FileField(upload_to='pdfs/')),
                ('evrak_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evrak_tags', models.ManyToManyField(blank=True, to='app_base.tag')),
            ],
        ),
    ]
