# Generated by Django 4.2.5 on 2023-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0008_evrakmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islemler',
            name='miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
