# Generated by Django 4.2.5 on 2023-11-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0008_islemler_exelusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exelusers',
            name='surname',
        ),
        migrations.AlterField(
            model_name='muuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
