# Generated by Django 4.2.5 on 2023-10-19 21:29

import app_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0009_alter_islemler_miktar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evrakmodel',
            name='evrak_type',
            field=models.CharField(choices=[('gelen', 'Gelen'), ('giden', 'Giden')], default='gelen', max_length=7),
        ),
        migrations.AlterField(
            model_name='evrakmodel',
            name='evrak_pdf',
            field=models.FileField(upload_to=app_base.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='evrakmodel',
            name='evrak_picture',
            field=models.ImageField(upload_to=app_base.models.generate_unique_imagename),
        ),
        migrations.CreateModel(
            name='EtkinlikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_date', models.DateTimeField(auto_now_add=True)),
                ('etkinlik_name', models.CharField(max_length=250)),
                ('etkinlik_description', models.TextField()),
                ('etkinlik_youtubelink', models.CharField(max_length=200)),
                ('etkinlik_picture', models.ImageField(upload_to=app_base.models.generate_unique_imagename)),
                ('etkinlik_tags', models.ManyToManyField(blank=True, to='app_base.tag')),
            ],
        ),
    ]
