# Generated by Django 4.2.5 on 2023-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0009_remove_exelusers_surname_alter_muuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mobile_files/')),
            ],
        ),
    ]
