# Generated by Django 4.2.5 on 2023-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0010_evrakmodel_evrak_type_alter_evrakmodel_evrak_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmodel',
            name='etkinlik_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evrakmodel',
            name='evrak_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
