# Generated by Django 4.2.5 on 2023-10-19 22:02

import app_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_etkinlikmodel_etkinlik_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='etkinlik_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='etkinlik_youtubelink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evrakmodel',
            name='evrak_pdf',
            field=models.FileField(blank=True, null=True, upload_to=app_base.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='evrakmodel',
            name='evrak_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename),
        ),
    ]
