# Generated by Django 4.2.5 on 2023-12-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_currency_is_active_etkinlikmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='muuser',
            managers=[
            ],
        ),
    ]
