# Generated by Django 4.2.5 on 2023-10-19 22:37

import app_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0012_alter_etkinlikmodel_etkinlik_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='islemler',
            name='islemler_pdf',
            field=models.FileField(blank=True, null=True, upload_to=app_base.models.generate_unique_filename),
        ),
        migrations.AddField(
            model_name='islemler',
            name='islemler_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app_base.models.generate_unique_imagename),
        ),
    ]
