# Generated by Django 4.2.5 on 2023-12-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0012_alter_muuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mugroup',
            options={'verbose_name': 'MuGroup', 'verbose_name_plural': 'MuGroups'},
        ),
    ]
