# Generated by Django 4.2.5 on 2023-12-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0013_alter_mugroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_base.currency'),
        ),
    ]
