# Generated by Django 4.2.5 on 2023-12-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0015_alter_islemler_miktar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mugroup',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mugroup',
            managers=[
            ],
        ),
    ]
