# Generated by Django 4.2.5 on 2023-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0016_alter_mugroup_options_alter_mugroup_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='etkinlik_youtubelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
