# Generated by Django 4.2.5 on 2023-12-09 19:38

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0017_alter_etkinlikmodel_etkinlik_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='etkinlik_youtubelink',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
