# Generated by Django 4.2.5 on 2024-01-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0021_alter_islemler_islemler_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mugroup',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='can_delete'),
        ),
        migrations.AddField(
            model_name='mugroup',
            name='can_write',
            field=models.BooleanField(default=False, verbose_name='can_write'),
        ),
    ]
