# Generated by Django 4.2.5 on 2024-01-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0022_mugroup_can_delete_mugroup_can_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mugroup',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='silebilme'),
        ),
        migrations.AlterField(
            model_name='mugroup',
            name='can_write',
            field=models.BooleanField(default=False, verbose_name='yazabilme'),
        ),
    ]
