# Generated by Django 4.2.6 on 2024-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0025_alter_mugroup_yetkiler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yetkiler',
            old_name='can_read_Islemleretkinlikler',
            new_name='can_read_Islemler',
        ),
        migrations.RenameField(
            model_name='yetkiler',
            old_name='can_write_Islemleretkinlikler',
            new_name='can_read_etkinlikler',
        ),
        migrations.AddField(
            model_name='yetkiler',
            name='can_read_para_birimleri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetkiler',
            name='can_write_Islemler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetkiler',
            name='can_write_etkinlikler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetkiler',
            name='can_write_para_birimleri',
            field=models.BooleanField(default=False),
        ),
    ]
